### ISSUE TITLE
I am getting  error 

### ISSUE THREAD

**Issue by praveenpotla** [harshitgindra/ImageShare.Xamarin#2]
{Android.Util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <26521a5118b44c858c385715922b9d5d>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <26521a5118b44c858c385715922b9d5d>:0 
  at Android.Content.ContextWrapper.StartActivity (Android.Content.Intent intent) [0x00031] in <4ccdb3137d974856b786e1aeebbfbab6>:0 
  at Event_Project.Droid.Helpers.ShareImage.Share (System.Byte[] bytes) [0x000b0] in E:\Git-TFS\Galactic\Phase-II\Event_Project\Event_Project.Android\Helpers\ShareImage.cs:70 
  at Event_Project.SocialSection.PinchImageViewer.share_Clicked (System.Object sender, System.EventArgs e) [0x00054] in E:\Git-TFS\Galactic\Phase-II\Event_Project\Event_Project\SocialSection\PinchImageViewer.xaml.cs:111 
  --- End of managed Android.Util.AndroidRuntimeException stack trace ---
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1040)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1009)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
	at crc643f46942d9dd1fff9.GenericMenuClickListener.n_onMenuItemClick(Native Method)
	at crc643f46942d9dd1fff9.GenericMenuClickListener.onMenuItemClick(GenericMenuClickListener.java:30)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:321)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1234)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3234)
	at android.widget.AbsListView$3.run(AbsListView.java:4210)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by harshitgindra** [comment]
This issue has been resolved. Seems that the android library have been updated. Implementation have been refactored to use Xamarin.Essentials library for sharing files.
